In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
tdf=pd.read_csv('faa_ai_prelim.csv')

In [4]:
tdf.head()

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UPDATED              83 non-null     object
 1   ENTRY_DATE           83 non-null     object
 2   EVENT_LCL_DATE       83 non-null     object
 3   EVENT_LCL_TIME       83 non-null     object
 4   LOC_CITY_NAME        83 non-null     object
 5   LOC_STATE_NAME       83 non-null     object
 6   LOC_CNTRY_NAME       2 non-null      object
 7   RMK_TEXT             83 non-null     object
 8   EVENT_TYPE_DESC      83 non-null     object
 9   FSDO_DESC            81 non-null     object
 10  REGIST_NBR           83 non-null     object
 11  FLT_NBR              6 non-null      object
 12  ACFT_OPRTR           7 non-null      object
 13  ACFT_MAKE_NAME       78 non-null     object
 14  ACFT_MODEL_NAME      79 non-null     object
 15  ACFT_MISSING_FLAG    0 non-null      float64
 16  ACFT_DMG_DESC        82 non-null     object
 17  FLT_ACTIVITY         13 non-null     object
 18  FLT_PHASE            82 non-null     object
 19  FAR_PART             1 non-null      float64
 20  MAX_INJ_LVL          80 non-null     object
 21  FATAL_FLAG           8 non-null      object
 22  FLT_CRW_INJ_NONE     64 non-null     float64
 23  FLT_CRW_INJ_MINOR    6 non-null      float64
 24  FLT_CRW_INJ_SERIOUS  1 non-null      float64
 25  FLT_CRW_INJ_FATAL    8 non-null      float64
 26  FLT_CRW_INJ_UNK      0 non-null      float64
 27  CBN_CRW_INJ_NONE     0 non-null      float64
 28  CBN_CRW_INJ_MINOR    0 non-null      float64
 29  CBN_CRW_INJ_SERIOUS  0 non-null      float64
 30  CBN_CRW_INJ_FATAL    0 non-null      float64
 31  CBN_CRW_INJ_UNK      1 non-null      float64
 32  PAX_INJ_NONE         17 non-null     float64
 33  PAX_INJ_MINOR        1 non-null      float64
 34  PAX_INJ_SERIOUS      3 non-null      float64
 35  PAX_INJ_FATAL        1 non-null      float64
 36  PAX_INJ_UNK          0 non-null      float64
 37  GRND_INJ_NONE        0 non-null      float64
 38  GRND_INJ_MINOR       0 non-null      float64
 39  GRND_INJ_SERIOUS     0 non-null      float64
 40  GRND_INJ_FATAL       0 non-null      float64
 41  GRND_INJ_UNK         1 non-null      float64
dtypes: float64(22), object(20)
memory usage: 27.4+ KB

In [6]:
df=tdf[['ACFT_MAKE_NAME','LOC_STATE_NAME','ACFT_MODEL_NAME',
        'RMK_TEXT','FLT_PHASE','EVENT_TYPE_DESC','FATAL_FLAG']]

In [7]:
df.head()

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df['FATAL_FLAG'].isnull().sum()

75

In [10]:
df['FATAL_FLAG'].fillna('No',inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [12]:
df['FATAL_FLAG'].isnull().sum()

0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ACFT_MAKE_NAME   78 non-null     object
 1   LOC_STATE_NAME   83 non-null     object
 2   ACFT_MODEL_NAME  79 non-null     object
 3   RMK_TEXT         83 non-null     object
 4   FLT_PHASE        82 non-null     object
 5   EVENT_TYPE_DESC  83 non-null     object
 6   FATAL_FLAG       83 non-null     object
dtypes: object(7)
memory usage: 4.7+ KB

In [15]:
df=df.dropna(subset=['ACFT_MAKE_NAME'])

In [16]:
df.shape

(78, 7)

In [19]:
for i in range(78):
    if(df['FATAL_FLAG'].iloc[i]=='Yes'):
        print(df.iloc[i])
        print('\n\n')

ACFT_MAKE_NAME                                                 BEECH
LOC_STATE_NAME                                        North Carolina
ACFT_MODEL_NAME                                                   36
RMK_TEXT           AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 0, dtype: object



ACFT_MAKE_NAME                                                 PIPER
LOC_STATE_NAME                                               Florida
ACFT_MODEL_NAME                                                 PA28
RMK_TEXT           AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 53, dtype: object



ACFT_MAKE_NAME                                         FLIGHT DESIGN
LOC_STATE_NAME                                            California
ACFT_MODEL_NAME                                                 CTLS
RMK_TEXT           AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 55, dtype: object



ACFT_MAKE_NAME                                        NORTH AMERICAN
LOC_STATE_NAME                                               Arizona
ACFT_MODEL_NAME                                                  F51
RMK_TEXT           AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 79, dtype: object



ACFT_MAKE_NAME                                              CHAMPION
LOC_STATE_NAME                                            California
ACFT_MODEL_NAME                                                8KCAB
RMK_TEXT           N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 80, dtype: object



ACFT_MAKE_NAME                                                 BEECH
LOC_STATE_NAME                                            California
ACFT_MODEL_NAME                                                   35
RMK_TEXT           N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 81, dtype: object



ACFT_MAKE_NAME                                                CESSNA
LOC_STATE_NAME                                               Alabama
ACFT_MODEL_NAME                                                  182
RMK_TEXT           N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...
FLT_PHASE                                              UNKNOWN (UNK)
EVENT_TYPE_DESC                                             Accident
FATAL_FLAG                                                       Yes
Name: 82, dtype: object

In [20]:
aircraft_type=df.groupby('ACFT_MAKE_NAME')

In [21]:
type(aircraft_type)

pandas.core.groupby.generic.DataFrameGroupBy

In [24]:
aircraft_type.first()

,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
ACFT_MAKE_NAME,,,,,,
AERO COMMANDER,Virginia,500,"AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE, VA",TAXI (TXI),Incident,No
AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,No
AEROSTAR INTERNATIONAL,California,RX8,"N3647A AEROSTAR INTERNATIONAL RX8 BALLOON, ON ...",LANDING (LDG),Accident,No
AIRBUS,Minnesota,A319,AMERICAN AIRLINES FLIGHT AAL476 AIRBUS A319 AI...,UNKNOWN (UNK),Accident,No
BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
BELL,Hawaii,206,N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...,UNKNOWN (UNK),Accident,No
BOEING,Florida,747,N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...,TAKEOFF (TOF),Incident,No
CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,No
CHAMPION,California,8KCAB,AIRCRAFT ON LANDING GROUND LOOPED AND GEAR COL...,LANDING (LDG),Accident,No
CHRISTEN,Louisiana,EAGLE II,AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...,TAKEOFF (TOF),Accident,No
CONSOLIDATED VULTEE,California,BT15,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...",TAXI (TXI),Incident,No
EMBRAER,Massachusetts,ERJ190,N273JB JETBLUE FLIGHT JBU891 EMBRAER ERJ190 AI...,STANDING (STD),Incident,No
ENSTROM,Michigan,None,"N180TH ENTROM TH180 HELICOPTER, FORCE LANDED ...",LANDING (LDG),Incident,No
FAIRCHILD,Texas,PT19,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, WES...",TAXI (TXI),Incident,No
FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes
GLOBE,Colorado,GC1B,"AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...",LANDING (LDG),Incident,No
GREAT LAKES,California,2T1A,"AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...",LANDING (LDG),Incident,No
GRUMMAN,California,AA1,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, SALIN...",LANDING (LDG),Incident,No
GULFSTREAM,Virginia,GULFSTREAM200,"AIRCRAFT ON TAXI COLLIDED WITH A VEHICLE, WASH...",TAXI (TXI),Incident,No
HUGHES,West Virginia,369,N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...,LANDING (LDG),Incident,No
LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,No
MAULE,Alaska,M4,"AIRCRAFT ON TAKEOFF STRUCK A TAXIWAY SIGN, ANC...",TAKEOFF (TOF),Incident,No
MOONEY,California,M20M,"AIRCRAFT ON LANDING GEAR COLLAPSED, NAPA, CA",LANDING (LDG),Incident,No
NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
PIPER,Florida,PA24,"AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...",LANDING (LDG),Incident,No
PITTS,California,S2,"AIRCRAFT, N704SL CESSNA 150, AND N57BC AVIAT ...",UNKNOWN (UNK),Accident,No
SAAB,Florida,340,N341AG SILVER AIRWAYS FLIGHT SIL70 SAAB 340B A...,STANDING (STD),Incident,No
SABRELINER,Arkansas,NA265,"AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...",LANDING (LDG),Incident,No
SOCATA,Arkansas,TB9,AIRCRAFT ON TAXI WING STRUCK THE PAVEMENT AND ...,TAXI (TXI),Incident,No
VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No

In [25]:
aircraft_type.size()

ACFT_MAKE_NAME
AERO COMMANDER             1
AERONCA                    1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
BEECH                      9
BELL                       2
BOEING                     3
CESSNA                    23
CHAMPION                   2
CHRISTEN                   1
CONSOLIDATED VULTEE        1
EMBRAER                    1
ENSTROM                    1
FAIRCHILD                  1
FLIGHT DESIGN              1
GLOBE                      1
GREAT LAKES                1
GRUMMAN                    1
GULFSTREAM                 1
HUGHES                     1
LANCAIR                    2
MAULE                      1
MOONEY                     4
NORTH AMERICAN             1
PIPER                     10
PITTS                      1
SAAB                       1
SABRELINER                 1
SOCATA                     2
VANS                       1
dtype: int64

In [26]:
Acc_fatal=df.groupby('FATAL_FLAG')

In [27]:
Acc_fatal.size()

FATAL_FLAG
No     71
Yes     7
dtype: int64

In [28]:
final=Acc_fatal.get_group('Yes')

In [29]:
final

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,Yes
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes

In [30]:
type(final)

pandas.core.frame.DataFrame